platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-orca/clang-toolchain
    tag: 0.2

inputs:
  - name: gpdb_src
    path: .
run:
  path: /bin/bash
  args:
  - -exc
  - |
    exit 1
params:
  CLANG_FORMAT: clang-format-11
