---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpdb_src
- name: gpaddon_src

outputs:
- name: gpAux_ext
- name: gphdfs_dist


run:
  path: gpdb_src/concourse/scripts/sync_tools.bash

params:
  TARGET_OS:
  TARGET_OS_VERSION:
  TASK_OS:
  TASK_OS_VERSION:
